# sharding sphere
spring:
  shardingsphere:
    datasource:
      names: ds-order-master, ds-order-slave0, ds-order-slave1, ds-user-master, ds-user-slave0
      ds-order-master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db_order_master?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: shucunbin
        password: '!123456$'
      ds-order-slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db_order_slave0?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: shucunbin
        password: '!123456$'
      ds-order-slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db_order_slave1?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: shucunbin
        password: '!123456$'
      ds-user-master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db_user_master?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: shucunbin
        password: '!123456$'
      ds-user-slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db_user_slave0?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: shucunbin
        password: '!123456$'
    sharding:
      master-slave-rules:
        order_ms:
          load-balance-algorithm-type: round_robin
          master-data-source-name: ds-order-master
          slave-data-source-names: ds-order-slave0,ds-order-slave1
        user_ms:
          load-balance-algorithm-type: round_robin
          master-data-source-name: ds-user-master
          slave-data-source-names: ds-user-slave0
      tables:
        t_order:
          actual-data-nodes: order_ms.t_order_$->{0..2}
          table-strategy:
            inline:
              sharding-column: order_id
              algorithm-expression: t_order_$->{order_id % 3}
          key-generator:
            column: id
            type: SNOWFLAKE
        t_user:
          actual-data-nodes: user_ms.t_user
      defaultTableStrategy:
        none:
    props:
      sql:
        show: true