# sharding sphere
spring:
  shardingsphere:
    datasource:
      names: ds-order-master-0,ds-order-master-1,ds-order-master-0-slave-0,ds-order-master-0-slave-1,ds-order-master-1-slave-0,
             ds-order-master-1-slave-1, ds-user
      ds-order-master-0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db_order_master_0?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: shucunbin
        password: '!123456$'
      ds-order-master-0-slave-0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db_order_master_0_slave_0?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: shucunbin
        password: '!123456$'
      ds-order-master-0-slave-1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db_order_master_0_slave_1?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: shucunbin
        password: '!123456$'
      ds-order-master-1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db_order_master_1?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: shucunbin
        password: '!123456$'
      ds-order-master-1-slave-0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db_order_master_1_slave_0?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: shucunbin
        password: '!123456$'
      ds-order-master-1-slave-1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db_order_master_1_slave_1?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: shucunbin
        password: '!123456$'
      ds-user:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db_user?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: shucunbin
        password: '!123456$'
    sharding:
      master-slave-rules:
        ds-order-ms-0:
          load-balance-algorithm-type: round_robin
          master-data-source-name: ds-order-master-0
          slave-data-source-names: ds-order-master-0-slave-0,ds-order-master-0-slave-1
        ds-order-ms-1:
          load-balance-algorithm-type: round_robin
          master-data-source-name: ds-order-master-1
          slave-data-source-names: ds-order-master-1-slave-0,ds-order-master-1-slave-1
      default-database-strategy:
        none:
      defaultTableStrategy:
        none:
      tables:
        t_order:
          actual-data-nodes: ds-order-ms-$->{0..1}.t_order_$->{0..2}
          database-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: ds-order-ms-$->{user_id % 2}
          table-strategy:
            inline:
              sharding-column: order_id
              algorithm-expression: t_order_$->{order_id % 3}
          key-generator:
            column: order_id
            type: SNOWFLAKE
        t_order_item:
          actual-data-nodes: ds-order-ms-$->{0..1}.t_order_item_$->{0..2}
          database-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: ds-order-ms-$->{user_id % 2}
          table-strategy:
            inline:
              sharding-column: order_id
              algorithm-expression: t_order_item_$->{order_id % 3}
          key-generator:
            column: order_item_id
            type: SNOWFLAKE
            props:
              max.vibration.offset: 2
              worker.id: 100
#        t_user:
#          actual-data-nodes: ds-user.t_user
      binding-tables: t_order, t_order_item
      default-data-source-name: ds-user
    props:
      sql:
        show: true