# sharding sphere
spring:
  shardingsphere:
    datasource:
      names: ds-order-0, ds-order-1
      ds-order-0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db_order_0?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: shucunbin
        password: '!123456$'
      ds-order-1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db_order_1?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: shucunbin
        password: '!123456$'
    sharding:
      default-database-strategy:
        inline:
          sharding-column: user_id
          algorithm-expression: ds-order-$->{user_id % 2}
      tables:
        t_order:
          actual-data-nodes: ds-order-$->{0..1}.t_order_$->{0..2}
          table-strategy:
            inline:
              sharding-column: order_id
              algorithm-expression: t_order_$->{order_id % 3}
          key-generator:
            column: order_id
            type: SNOWFLAKE
            props:
              max.vibration.offset: 2
              worker.id: 100
        t_order_item:
          actual-data-nodes: ds-order-$->{0..1}.t_order_item_$->{0..2}
          table-strategy:
            inline:
              sharding-column: order_id
              algorithm-expression: t_order_item_$->{order_id % 3}
          key-generator:
            column: order_item_id
            type: SNOWFLAKE
            props:
              max.vibration.offset: 2
              worker.id: 100
      defaultTableStrategy:
        none:
      binding-tables: t_order, t_order_item
    props:
      sql:
        show: true