# sharding sphere - master-slave config
spring:
  shardingsphere:
    datasource:
      names: ds-user
      ds-user:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db_user?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: shucunbin
        password: '!123456$'
    encrypt:
      encryptors:
        user_name_encryptor:
          type: aes
          props:
            aes.key.value: 123456abc
      tables:
        t_user:
          columns:
            user_name:
#              plainColumn: user_name
              cipherColumn: user_name_cipher
              encryptor: user_name_encryptor
    props:
      sql:
        show: true
      query:
        with.cipher.comlum: true