# sharding sphere
spring:
  shardingsphere:
    datasource:
      names: ds-order
      ds-order:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db_order_master?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: shucunbin
        password: '!123456$'
    sharding:
      tables:
        t_order:
          actual-data-nodes: ds-order.t_order_$->{0..2}
          table-strategy:
            inline:
              sharding-column: order_id
              algorithm-expression: t_order_$->{order_id % 3}
          key-generator:
            column: order_id
            type: SNOWFLAKE
            props:
              max.vibration.offset: 2
              worker.id: 100
        t_order_item:
          actual-data-nodes: ds-order.t_order_item_$->{0..2}
          table-strategy:
            inline:
              sharding-column: order_id
              algorithm-expression: t_order_item_$->{order_id % 3}
          key-generator:
            column: order_item_id
            type: SNOWFLAKE
            props:
              max.vibration.offset: 2
              worker.id: 100
      defaultTableStrategy:
        none:
      binding-tables: t_order,t_order_item
    props:
      sql:
        show: true