# 读写分离
#spring:
#  profiles:
#    active: master-slave


# 分表
#spring:
#  profiles:
#    active: sharding-tables


# 分库
#spring:
#  profiles:
#    active: sharding-databases


# 分库分表
#spring:
#  profiles:
#    active: sharding-databases-tables


# 读写分离 + 分库分表
spring:
  profiles:
    active: sharding-master-slave