# sharding sphere - master-slave config
spring:
  shardingsphere:
    datasource:
      names: ds-user-master, ds-user-slave1
      ds-user-master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db_user?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: shucunbin
        password: '!123456$'
      ds-user-slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db_user?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: shucunbin
        password: '!123456$'
#      ds-user-slave2:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:33062/db_user_slave1?useSSL=false&useUnicode=true&characterEncoding=UTF-8
#        username: root
#        password: '!master&root&pw'
    sharding:
      master-slave-rules:
        user_ms:
          load-balance-algorithm-type: round_robin
          master-data-source-name: ds-user-master
          slave-data-source-names: ds-user-slave1
    props:
      sql:
        show: true