# 读写分离
spring:
  profiles:
    active: master-slave-v2


# 分表
#spring:
#  profiles:
#    active: sharding-tables


# 分库
#spring:
#  profiles:
#    active: sharding-databases


# 分库分表
#spring:
#  profiles:
#    active: sharding-databases-tables


# 读写分离 + 分库分表
#spring:
#  profiles:
#    active: sharding-master-slave


# 读写分离 + 分库分表 + 普通库
#spring:
#  profiles:
#    active: sharding-master-slave-v2